// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ondato.Data;

namespace Ondato.Data.Migrations
{
    [DbContext(typeof(KeyValueStoreContext))]
    partial class KeyValueStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ondato.Data.KeyValuePair", b =>
                {
                    b.Property<string>("KeyJson")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyJson");

                    b.ToTable("KeyValuePairs");
                });
#pragma warning restore 612, 618
        }
    }
}
